// Engine parity tests.
//
// Loads JSON fixtures generated by `tools/engine_parity_fixtures.py`
// (scripted Python games with state snapshots after every action).
// Replays the same actions through the TS Game/Match and asserts
// state-equivalence at every checkpoint.

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import type { CardId } from '../card';
import { Game } from '../game';
import type { Seat, Team } from '../seating';
import type {
  BiddingState,
  CapsCall,
  CapsObligation,
  CompletedRound,
  GameResult,
  GameState,
  PlayState,
  RoundEntry,
  TrumpState,
} from '../state';
import type { BidAction } from '../types';

const FIXTURE_DIR = join(__dirname, 'parity-fixtures');

interface FixtureAction {
  type:
    | 'bid'
    | 'select_trump'
    | 'open_trump'
    | 'closed_trump'
    | 'play'
    | 'call_caps'
    | 'spoilt'
    | 'absolute';
  seat?: string;
  action?: string;
  value?: number | null;
  card?: string;
  revealCard?: string | null;
  playOrder?: string[];
}

interface Fixture {
  name: string;
  dealer: string;
  hands: Record<string, string[]>;
  initialSnapshot: SnapshotJson;
  actions: FixtureAction[];
  checkpoints: SnapshotJson[];
}

// Mirror the Python snapshot shape (snake-cased keys translated to
// camelCase by the Python serializer already).
interface SnapshotJson {
  gameNumber: number;
  dealer: string;
  phase: string;
  stone: Record<string, number>;
  hands: Record<string, string[]>;
  trump: TrumpJson;
  bidding: BiddingJson | null;
  play: PlayJson | null;
  result: ResultJson | null;
  consecutiveReshuffles: number;
  pccPartnerOut: string | null;
}

interface TrumpJson {
  trumperSeat: string | null;
  trumpSuit: string | null;
  trumpCard: string | null;
  isRevealed: boolean;
  isOpen: boolean;
  trumpCardInHand: boolean;
}

interface BiddingJson {
  isFourCard: boolean;
  currentBidder: string;
  highestBid: number;
  highestBidder: string | null;
  consecutivePasses: number;
  speeches: SpeechJson[];
  playerState: Record<string, PlayerBidStateJson>;
  isPcc: boolean;
  pendingPartner: { originalSeat: string; partnerSeat: string } | null;
  fourCardBid: number | null;
  fourCardBidder: string | null;
}

interface SpeechJson {
  seat: string;
  action: string;
  value: number | null;
  speechNumber: number;
  onBehalfOf: string | null;
}

interface PlayerBidStateJson {
  speechCount: number;
  hasPartnered: boolean;
  partnerUsedBy: string | null;
  skipped: boolean;
}

interface PlayJson {
  roundNumber: number;
  priority: string | null;
  currentTurn: string | null;
  currentRound: RoundEntryJson[];
  completedRounds: CompletedRoundJson[];
  pointsWon: Record<string, number>;
  capsCall: CapsCallJson | null;
  capsObligations: Record<string, CapsObligationJson>;
}

interface RoundEntryJson {
  seat: string;
  card: string | null;
  faceDown: boolean;
  revealed: boolean;
}

interface CompletedRoundJson {
  roundNumber: number;
  cards: RoundEntryJson[];
  winner: string;
  pointsWon: number;
  trumpRevealed: boolean;
}

interface CapsObligationJson {
  obligatedAtRound: number;
  obligatedAtCard: number;
  vPlaysAtObligation: number;
}

interface CapsCallJson {
  calledBy: string;
  calledAtRound: number;
  playOrder: string[];
  isExternal: boolean;
  result: string | null;
}

interface ResultJson {
  reason: string;
  stoneExchanged: number;
  stoneDirection: string;
  winnerTeam: string | null;
  description: string;
  trumperPoints: number | null;
  oppositionPoints: number | null;
  bid: number | null;
  capsBy: string | null;
}

// ---------------------------------------------------------------------------
// Snapshotting (TS GameState → JSON)
// ---------------------------------------------------------------------------

const SEATS_VALS: Seat[] = ['north', 'west', 'south', 'east'];
const TEAMS_VALS: Team[] = ['team_a', 'team_b'];

const trumpJson = (t: TrumpState): TrumpJson => ({
  trumperSeat: t.trumperSeat,
  trumpSuit: t.trumpSuit,
  trumpCard: t.trumpCard,
  isRevealed: t.isRevealed,
  isOpen: t.isOpen,
  trumpCardInHand: t.trumpCardInHand,
});

const speechJson = (s: BiddingState['speeches'][number]): SpeechJson => ({
  seat: s.seat,
  action: s.action,
  value: s.value,
  speechNumber: s.speechNumber,
  onBehalfOf: s.onBehalfOf,
});

const biddingJson = (b: BiddingState | null): BiddingJson | null => {
  if (b === null) return null;
  const playerState: Record<string, PlayerBidStateJson> = {};
  for (const seat of SEATS_VALS) {
    const ps = b.playerState[seat];
    playerState[seat] = {
      speechCount: ps.speechCount,
      hasPartnered: ps.hasPartnered,
      partnerUsedBy: ps.partnerUsedBy,
      skipped: ps.skipped,
    };
  }
  return {
    isFourCard: b.isFourCard,
    currentBidder: b.currentBidder,
    highestBid: b.highestBid,
    highestBidder: b.highestBidder,
    consecutivePasses: b.consecutivePasses,
    speeches: b.speeches.map(speechJson),
    playerState,
    isPcc: b.isPcc,
    pendingPartner: b.pendingPartner
      ? {
          originalSeat: b.pendingPartner.originalSeat,
          partnerSeat: b.pendingPartner.partnerSeat,
        }
      : null,
    fourCardBid: b.fourCardBid,
    fourCardBidder: b.fourCardBidder,
  };
};

const roundEntryJson = (e: RoundEntry): RoundEntryJson => ({
  seat: e.seat,
  card: e.card,
  faceDown: e.faceDown,
  revealed: e.revealed,
});

const completedRoundJson = (r: CompletedRound): CompletedRoundJson => ({
  roundNumber: r.roundNumber,
  cards: r.cards.map(roundEntryJson),
  winner: r.winner,
  pointsWon: r.pointsWon,
  trumpRevealed: r.trumpRevealed,
});

const capsObligationJson = (o: CapsObligation): CapsObligationJson => ({
  obligatedAtRound: o.obligatedAtRound,
  obligatedAtCard: o.obligatedAtCard,
  vPlaysAtObligation: o.vPlaysAtObligation,
});

const capsCallJson = (c: CapsCall | null): CapsCallJson | null => {
  if (c === null) return null;
  return {
    calledBy: c.calledBy,
    calledAtRound: c.calledAtRound,
    playOrder: [...c.playOrder],
    isExternal: c.isExternal,
    result: c.result,
  };
};

const playJson = (p: PlayState | null): PlayJson | null => {
  if (p === null) return null;
  const obligations: Record<string, CapsObligationJson> = {};
  for (const [seat, ob] of p.capsObligations.entries()) {
    obligations[seat] = capsObligationJson(ob);
  }
  return {
    roundNumber: p.roundNumber,
    priority: p.priority,
    currentTurn: p.currentTurn,
    currentRound: p.currentRound.map(roundEntryJson),
    completedRounds: p.completedRounds.map(completedRoundJson),
    pointsWon: { team_a: p.pointsWon.team_a, team_b: p.pointsWon.team_b },
    capsCall: capsCallJson(p.capsCall),
    capsObligations: obligations,
  };
};

const resultJson = (r: GameResult | null): ResultJson | null => {
  if (r === null) return null;
  return {
    reason: r.reason,
    stoneExchanged: r.stoneExchanged,
    stoneDirection: r.stoneDirection,
    winnerTeam: r.winnerTeam,
    description: r.description,
    trumperPoints: r.trumperPoints ?? null,
    oppositionPoints: r.oppositionPoints ?? null,
    bid: r.bid ?? null,
    capsBy: r.capsBy ?? null,
  };
};

const snapshot = (state: GameState): SnapshotJson => {
  const hands: Record<string, string[]> = {};
  for (const seat of SEATS_VALS) {
    hands[seat] = [...(state.hands[seat] ?? [])];
  }
  const stone: Record<string, number> = {};
  for (const team of TEAMS_VALS) stone[team] = state.stone[team];
  return {
    gameNumber: state.gameNumber,
    dealer: state.dealer,
    phase: state.phase,
    stone,
    hands,
    trump: trumpJson(state.trump),
    bidding: biddingJson(state.bidding),
    play: playJson(state.play),
    result: resultJson(state.result),
    consecutiveReshuffles: state.consecutiveReshuffles,
    pccPartnerOut: state.pccPartnerOut,
  };
};

// ---------------------------------------------------------------------------
// Action driver
// ---------------------------------------------------------------------------

const applyAction = (game: Game, action: FixtureAction): void => {
  switch (action.type) {
    case 'bid':
      game.placeBid(
        action.seat as Seat,
        action.action as BidAction,
        action.value ?? 0,
      );
      return;
    case 'select_trump':
      game.selectTrump(action.seat as Seat, action.card as CardId);
      return;
    case 'open_trump':
      game.declareOpenTrump(
        action.seat as Seat,
        (action.revealCard ?? null) as CardId | null,
      );
      return;
    case 'closed_trump':
      game.proceedClosedTrump(action.seat as Seat);
      return;
    case 'play':
      game.playCard(action.seat as Seat, action.card as CardId);
      return;
    case 'call_caps':
      game.callCaps(
        action.seat as Seat,
        (action.playOrder ?? []) as CardId[],
      );
      return;
    case 'spoilt':
      game.callSpoiltTrumps(action.seat as Seat);
      return;
    case 'absolute':
      game.callAbsoluteHand(action.seat as Seat);
      return;
  }
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const fixtureFiles = readdirSync(FIXTURE_DIR).filter(f => f.endsWith('.json'));

// Caps-obligation detection diverges between TS (CSP solver) and
// Python (world enumeration + witness search). Both target the same
// predicate but the algorithms are not bit-equivalent in all states.
// Since this divergence pre-dates the engine port, parity tests strip
// `capsObligations` before comparing; the dedicated caps tests in
// caps.test.ts cover the TS solver's behaviour.
const stripCapsObligations = (snap: SnapshotJson): SnapshotJson => {
  if (snap.play === null) return snap;
  return {
    ...snap,
    play: { ...snap.play, capsObligations: {} },
  };
};

describe('engine parity vs game304', () => {
  for (const file of fixtureFiles) {
    const fixture: Fixture = JSON.parse(
      readFileSync(join(FIXTURE_DIR, file), 'utf8'),
    );

    // Each fixture replays a full 8-round game through the engine and
    // takes ~3s alone, so the 5s default flaked whenever anything else
    // in the suite was competing for CPU.
    it(`replays ${fixture.name}`, () => {
      const game = new Game({ dealer: fixture.dealer as Seat });
      const hands: Record<Seat, CardId[]> = {
        north: fixture.hands.north as CardId[],
        west: fixture.hands.west as CardId[],
        south: fixture.hands.south as CardId[],
        east: fixture.hands.east as CardId[],
      };
      game.seedDeal(hands);

      expect(stripCapsObligations(snapshot(game.state))).toEqual(
        stripCapsObligations(fixture.initialSnapshot),
      );

      fixture.actions.forEach((action, i) => {
        applyAction(game, action);
        const expected = stripCapsObligations(fixture.checkpoints[i]);
        const actual = stripCapsObligations(snapshot(game.state));
        try {
          expect(actual).toEqual(expected);
        } catch (err) {
          console.error(
            `Mismatch at action ${i} (${action.type}) in ${fixture.name}:`,
            JSON.stringify(action),
          );
          throw err;
        }
      });
    }, 30_000);
  }
});
