#!/usr/bin/env python3
"""Generate engine parity fixtures.

Each fixture is a scripted 304 game played through ``game304.Game``.
The fixture records the initial deal, the sequence of actions, and a
state snapshot after each action. The TypeScript parity tests load
these fixtures and replay the actions through the TS engine,
asserting state-equivalence at every checkpoint.

Run from the repo root:

    python3 tools/engine_parity_fixtures.py

Output: frontend/src/304dle/engine/__tests__/parity-fixtures/*.json

Plays are auto-generated by an "always pick the lowest-power legal
card" policy, deterministic given the deal. Bidding and trump-select
actions are scripted.
"""
from __future__ import annotations

import json
import os
import sys
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from game304 import (  # noqa: E402
    BidAction,
    Card,
    Game,
    Seat,
)
from game304.types import Phase  # noqa: E402


OUT_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..",
    "frontend",
    "src",
    "304dle",
    "engine",
    "__tests__",
    "parity-fixtures",
)


# ---------------------------------------------------------------------------
# Snapshotting (full GameState → JSON)
# ---------------------------------------------------------------------------


def card_to_str(c: Card | None) -> str | None:
    return None if c is None else str(c)


def serialize_speech(speech: Any) -> dict[str, Any]:
    return {
        "seat": speech.seat.value,
        "action": speech.action.value,
        "value": speech.value,
        "speechNumber": speech.speech_number,
        "onBehalfOf": speech.on_behalf_of.value if speech.on_behalf_of else None,
    }


def serialize_player_bid_state(ps: Any) -> dict[str, Any]:
    return {
        "speechCount": ps.speech_count,
        "hasPartnered": ps.has_partnered,
        "partnerUsedBy": ps.partner_used_by.value if ps.partner_used_by else None,
        "skipped": ps.skipped,
    }


def serialize_bidding(b: Any) -> dict[str, Any] | None:
    if b is None:
        return None
    return {
        "isFourCard": b.is_four_card,
        "currentBidder": b.current_bidder.value,
        "highestBid": b.highest_bid,
        "highestBidder": b.highest_bidder.value if b.highest_bidder else None,
        "consecutivePasses": b.consecutive_passes,
        "speeches": [serialize_speech(s) for s in b.speeches],
        "playerState": {
            seat.value: serialize_player_bid_state(b.player_state[seat])
            for seat in Seat
            if seat in b.player_state
        },
        "isPcc": b.is_pcc,
        "pendingPartner": (
            {
                "originalSeat": b.pending_partner.original_seat.value,
                "partnerSeat": b.pending_partner.partner_seat.value,
            }
            if b.pending_partner
            else None
        ),
        "fourCardBid": b.four_card_bid,
        "fourCardBidder": b.four_card_bidder.value if b.four_card_bidder else None,
    }


def serialize_trump(t: Any) -> dict[str, Any]:
    return {
        "trumperSeat": t.trumper_seat.value if t.trumper_seat else None,
        "trumpSuit": t.trump_suit.value if t.trump_suit else None,
        "trumpCard": card_to_str(t.trump_card),
        "isRevealed": t.is_revealed,
        "isOpen": t.is_open,
        "trumpCardInHand": t.trump_card_in_hand,
    }


def serialize_round_entry(e: Any) -> dict[str, Any]:
    return {
        "seat": e.seat.value,
        "card": card_to_str(e.card),
        "faceDown": e.face_down,
        "revealed": e.revealed,
    }


def serialize_completed_round(r: Any) -> dict[str, Any]:
    return {
        "roundNumber": r.round_number,
        "cards": [serialize_round_entry(c) for c in r.cards],
        "winner": r.winner.value,
        "pointsWon": r.points_won,
        "trumpRevealed": r.trump_revealed,
    }


def serialize_caps_obligation(o: Any) -> dict[str, Any]:
    return {
        "obligatedAtRound": o.obligated_at_round,
        "obligatedAtCard": o.obligated_at_card,
        "vPlaysAtObligation": o.v_plays_at_obligation,
    }


def serialize_caps_call(c: Any) -> dict[str, Any] | None:
    if c is None:
        return None
    return {
        "calledBy": c.called_by.value,
        "calledAtRound": c.called_at_round,
        "playOrder": [str(card) for card in c.play_order],
        "isExternal": c.is_external,
        "result": c.result,
    }


def serialize_play(p: Any) -> dict[str, Any] | None:
    if p is None:
        return None
    return {
        "roundNumber": p.round_number,
        "priority": p.priority.value if p.priority else None,
        "currentTurn": p.current_turn.value if p.current_turn else None,
        "currentRound": [serialize_round_entry(e) for e in p.current_round],
        "completedRounds": [
            serialize_completed_round(r) for r in p.completed_rounds
        ],
        "pointsWon": {team.value: pts for team, pts in p.points_won.items()},
        "capsCall": serialize_caps_call(p.caps_call),
        "capsObligations": {
            seat.value: serialize_caps_obligation(o)
            for seat, o in p.caps_obligations.items()
        },
    }


def serialize_result(r: Any) -> dict[str, Any] | None:
    if r is None:
        return None
    return {
        "reason": r.reason,
        "stoneExchanged": r.stone_exchanged,
        "stoneDirection": r.stone_direction,
        "winnerTeam": r.winner_team.value if r.winner_team else None,
        "description": r.description,
        "trumperPoints": r.trumper_points,
        "oppositionPoints": r.opposition_points,
        "bid": r.bid,
        "capsBy": r.caps_by.value if r.caps_by else None,
    }


def snapshot(state: Any) -> dict[str, Any]:
    return {
        "gameNumber": state.game_number,
        "dealer": state.dealer.value,
        "phase": state.phase.value,
        "stone": {team.value: pts for team, pts in state.stone.items()},
        "hands": {
            seat.value: [str(c) for c in state.hands.get(seat, [])]
            for seat in Seat
        },
        "trump": serialize_trump(state.trump),
        "bidding": serialize_bidding(state.bidding),
        "play": serialize_play(state.play),
        "result": serialize_result(state.result),
        "consecutiveReshuffles": state.consecutive_reshuffles,
        "pccPartnerOut": state.pcc_partner_out.value if state.pcc_partner_out else None,
    }


# ---------------------------------------------------------------------------
# Action driver
# ---------------------------------------------------------------------------


def apply_action(game: Game, action: dict[str, Any]) -> None:
    t = action["type"]
    if t == "bid":
        game.place_bid(
            Seat(action["seat"]),
            BidAction(action["action"]),
            action.get("value", 0) or 0,
        )
    elif t == "select_trump":
        game.select_trump(Seat(action["seat"]), Card.from_str(action["card"]))
    elif t == "open_trump":
        rev = action.get("revealCard")
        game.declare_open_trump(
            Seat(action["seat"]), Card.from_str(rev) if rev else None,
        )
    elif t == "closed_trump":
        game.proceed_closed_trump(Seat(action["seat"]))
    elif t == "play":
        game.play_card(Seat(action["seat"]), Card.from_str(action["card"]))
    elif t == "call_caps":
        order = [Card.from_str(c) for c in action["playOrder"]]
        game.call_caps(Seat(action["seat"]), order)
    elif t == "spoilt":
        game.call_spoilt_trumps(Seat(action["seat"]))
    elif t == "absolute":
        game.call_absolute_hand(Seat(action["seat"]))
    else:
        raise ValueError(f"Unknown action type: {t}")


# ---------------------------------------------------------------------------
# Auto-play policy
# ---------------------------------------------------------------------------


def auto_play(game: Game) -> dict[str, Any]:
    """Pick a deterministic legal play: prefer the highest-power
    (Jack first) legal card. Returns the action dict.

    Rationale: trumps tend to be high-power cards, so this exercises
    cuts and trumping naturally without random choice.
    """
    seat = game.whose_turn()
    if seat is None:
        raise RuntimeError("auto_play called when no turn is pending")
    valid = game.valid_plays(seat)
    if not valid:
        raise RuntimeError(f"auto_play: no valid plays for {seat.value}")
    # Sort by (power, suit, rank) for determinism. Lower power = stronger.
    valid_sorted = sorted(valid, key=lambda c: (c.power, c.suit.value, c.rank.value))
    chosen = valid_sorted[0]
    return {"type": "play", "seat": seat.value, "card": str(chosen)}


# ---------------------------------------------------------------------------
# Fixture builder
# ---------------------------------------------------------------------------


def seed_deal(game: Game, hands: dict[Seat, list[Card]]) -> None:
    """Inject a pre-determined 8-cards-per-seat deal into a fresh Game.

    Replicates Python Game state at "post-deal_4 → about to start
    BETTING_4" with the second 4 cards held in the deck.
    """
    from game304.bidding import init_bidding_state
    from game304.deck import Deck
    from game304.seating import deal_order

    first_four = {seat: hands[seat][:4] for seat in Seat}
    order = deal_order(game.state.dealer)
    # Construct deck so dealer-side dealing in select_trump produces
    # each seat's second-four cards in order.
    reserve: list[Card] = []
    for seat in order:
        reserve.extend(hands[seat][4:])

    game.state.hands = {seat: list(first_four[seat]) for seat in Seat}
    game.state.deck = Deck(cards=reserve)
    game.state.phase = Phase.BETTING_4
    game.state.bidding = init_bidding_state(
        first_bidder=order[0], is_four_card=True
    )


def build_fixture(
    name: str,
    hands: dict[Seat, list[Card]],
    dealer: Seat,
    scripted_actions: list[dict[str, Any]],
    auto_play_until_complete: bool = True,
) -> dict[str, Any]:
    """Run a scripted game through Python and emit the fixture.

    `scripted_actions` are applied in order; once they're exhausted,
    if `auto_play_until_complete`, the game continues with auto_play
    actions until the phase reaches COMPLETE.
    """
    game = Game(dealer=dealer)
    seed_deal(game, hands)

    initial_snapshot = snapshot(game.state)
    actions: list[dict[str, Any]] = []
    checkpoints: list[dict[str, Any]] = []

    for action in scripted_actions:
        apply_action(game, action)
        actions.append(action)
        checkpoints.append(snapshot(game.state))

    if auto_play_until_complete:
        # Continue with auto_play during PLAYING; bail at COMPLETE/SCRUTINY.
        guard = 200
        while game.state.phase == Phase.PLAYING and guard > 0:
            action = auto_play(game)
            apply_action(game, action)
            actions.append(action)
            checkpoints.append(snapshot(game.state))
            guard -= 1
        if guard <= 0:
            raise RuntimeError("auto_play did not terminate within 200 plays")

    return {
        "name": name,
        "dealer": dealer.value,
        "hands": {
            seat.value: [str(c) for c in hands[seat]] for seat in Seat
        },
        "initialSnapshot": initial_snapshot,
        "actions": actions,
        "checkpoints": checkpoints,
    }


# ---------------------------------------------------------------------------
# Scenarios
# ---------------------------------------------------------------------------


def make_balanced_hands_a() -> dict[Seat, list[Card]]:
    """Diverse-suit hands: trumper (West) has clubs lead and a non-club."""
    layout = {
        Seat.NORTH: ["9h", "Ah", "10h", "Kh", "Qh", "8h", "7h", "Js"],
        Seat.WEST:  ["Jc", "9c", "Ac", "Kc", "Qd", "8c", "7c", "Jh"],
        Seat.SOUTH: ["10c", "9d", "Ad", "10d", "Kd", "Jd", "8d", "7d"],
        Seat.EAST:  ["9s", "As", "10s", "Ks", "Qs", "8s", "7s", "Qc"],
    }
    hands = {seat: [Card.from_str(c) for c in cs] for seat, cs in layout.items()}
    # Verify pack completeness.
    seen = sorted(str(c) for cs in hands.values() for c in cs)
    expected = sorted(
        f"{r}{s}" for s in "cdhs"
        for r in ["J", "9", "A", "10", "K", "Q", "8", "7"]
    )
    if seen != expected:
        raise ValueError(f"Layout invalid. Got {seen}; expected {expected}")
    return hands


def scenario_happy_closed_trump() -> dict[str, Any]:
    """Closed-trump game: West bids 160 on Jc. 8-card all pass. Closed play."""
    hands = make_balanced_hands_a()
    scripted: list[dict[str, Any]] = [
        # 4-card betting: order west, south, east, north.
        {"type": "bid", "seat": "west", "action": "bet", "value": 160},
        {"type": "bid", "seat": "south", "action": "pass"},
        {"type": "bid", "seat": "east", "action": "pass"},
        {"type": "bid", "seat": "north", "action": "pass"},
        # Trump select.
        {"type": "select_trump", "seat": "west", "card": "Jc"},
        # 8-card betting all pass.
        {"type": "bid", "seat": "west", "action": "pass"},
        {"type": "bid", "seat": "south", "action": "pass"},
        {"type": "bid", "seat": "east", "action": "pass"},
        {"type": "bid", "seat": "north", "action": "pass"},
        # Closed trump.
        {"type": "closed_trump", "seat": "west"},
    ]
    return build_fixture(
        "happy_closed_trump", hands, Seat.NORTH, scripted,
        auto_play_until_complete=True,
    )


def scenario_open_trump() -> dict[str, Any]:
    """Open-trump variant: West declares Open Trump before play."""
    hands = make_balanced_hands_a()
    scripted: list[dict[str, Any]] = [
        {"type": "bid", "seat": "west", "action": "bet", "value": 160},
        {"type": "bid", "seat": "south", "action": "pass"},
        {"type": "bid", "seat": "east", "action": "pass"},
        {"type": "bid", "seat": "north", "action": "pass"},
        {"type": "select_trump", "seat": "west", "card": "Jc"},
        {"type": "bid", "seat": "west", "action": "pass"},
        {"type": "bid", "seat": "south", "action": "pass"},
        {"type": "bid", "seat": "east", "action": "pass"},
        {"type": "bid", "seat": "north", "action": "pass"},
        {"type": "open_trump", "seat": "west", "revealCard": "9c"},
    ]
    return build_fixture(
        "open_trump", hands, Seat.NORTH, scripted,
        auto_play_until_complete=True,
    )


def scenario_pass_on() -> dict[str, Any]:
    """4-card pass-on: all 4 players pass; deal moves to next dealer."""
    hands = make_balanced_hands_a()
    scripted: list[dict[str, Any]] = [
        {"type": "bid", "seat": "west", "action": "pass"},
        {"type": "bid", "seat": "south", "action": "pass"},
        {"type": "bid", "seat": "east", "action": "pass"},
        {"type": "bid", "seat": "north", "action": "pass"},
    ]
    return build_fixture(
        "pass_on_4_card", hands, Seat.NORTH, scripted,
        auto_play_until_complete=False,
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    fixtures = [
        scenario_happy_closed_trump(),
        scenario_open_trump(),
        scenario_pass_on(),
    ]
    for fix in fixtures:
        out_path = os.path.join(OUT_DIR, f"{fix['name']}.json")
        with open(out_path, "w") as f:
            json.dump(fix, f, indent=2, sort_keys=True)
        print(f"wrote {out_path}  ({len(fix['checkpoints'])} checkpoints)")


if __name__ == "__main__":
    main()
